### ISSUE TITLE
Homepage Content & Design

### ISSUE THREAD

**Issue by vzrenggamani** [teknologi-pendidikan/pameran-karya#1]
# Gambaran Umum

Berdasarkan panduan atau [Konsep Situs Web](https://github.com/teknologi-pendidikan/pameran-karya/blob/main/docs/concept.md) bagian Informasi Pameran Karya, terdapat poin - poin yang harus ditampilkan pada [Halaman Utama](https://pamerankarya.teknologipendidikan.or.id) diantaranya:

1. Tanggal Pelaksanaan Pameran Karya
2. Lokasi Pelaksanaan Pameran Karya
3. Tema Pameran Karya
4. Deskripsi Singkat Pameran Karya
5. Panduan Umum bagi pengunjung
6. Panduan Umum bagi peserta pameran karya
7. Sponsor Pameran Karya

dari kebutuhan tersebut, diperlukan desain & konten yang akan dimediasikan ke dalam laman utama untuk memudahkan pencarian informasi serta SEO dari situs pameran karya tahun ini.

## Daftar Tugas

**Proses pra-Desain**
- [x] Konten Situs Web
   - [x] Tema pameran
   - [x] Tanggal pelaksanaan
   - [x] Tempat pelaksanaan
   - [x] Timeline pelaksanaan & kegiatan
   - [x] Panduan pameran untuk peserta & partisipan
   - [x] Copywriting promosi
 
**Proses Desain**
- [x] Desain situs web
- [x] Struktur konten
- [x] Demo karya untuk galeri

**Proses Implementasi**
- [x] Implementasi desain
- [x] E2E Testing
- [x] a11y WCAG AA Comply
- [x] Internal Performance Testing

**Pasca Implementasi**
- [x] SEO Check
- [x] Google Crawl Check
- [x] E2E Performance Testing

### Panduan Desain & Konten

Situs ini dibuat secara spesifik untuk tampilan desktop dengan resolusi `non-HD (1280 x 720)` dan resolusi tertinggi HD `(1920 x 1080)`. Meskipun demikian, tampilan mobile tetap terfasilitasi dengan layout visual yang cukup berbeda dengan tampilan desktop.

**Tampilan Mobile**
![image](https://user-images.githubusercontent.com/14950309/226426946-61f71028-fc5c-4822-89ba-47c515dc9192.png)

**Tampilan Desktop (1920x1080)**
![image](https://user-images.githubusercontent.com/14950309/226427140-aa762124-7f12-44d1-808f-3e9140b16a7c.png)

**Tampilan Desktop (1270 x 720)**
![image](https://user-images.githubusercontent.com/14950309/226427241-1dd6764d-249b-4b7e-82c2-39d8462c5378.png)

**Comment by vzrenggamani** [comment]
Fixed in [v1.0.0-rc.1+commit.3486deb](https://github.com/teknologi-pendidikan/pameran-karya/releases/tag/v1.0.0-rc.1%2Bcommit.3486deb)
